module_mira = "Mira"

msg_mira_enabled = "Mira is now %s in this channel."
huhu_mira = "Dear warrior of the light. remember to boot your routine or memory. $cc and be good!"
mira_enabled = "Mira Enabled?"
